import { INTERVALS } from '../intervals';

export const CHORDS: { [chordName: string]: string[] } = {
    'NOTE': [INTERVALS.ROOT],
    '5': [INTERVALS.ROOT, INTERVALS.PERFECT_5TH],
    'MAJOR': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH],
    'MINOR': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_5TH],
    'AUGMENTED': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.AUGMENTED_5TH],
    'DIMINISHED': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.DIMINISHED_5TH],

    'DOMINANT 7TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH],
    'DIMINISHED 7TH': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.DIMINISHED_5TH, INTERVALS.DIMINISHED_7TH],
    'HALF-DIMINISHED 7TH': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.DIMINISHED_5TH, INTERVALS.MINOR_7TH],
    'MINOR 7TH': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH],
    'MINOR MAJOR 7TH': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_7TH],
    'MAJOR 7TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_7TH],
    'AUGMENTED 7TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.AUGMENTED_5TH, INTERVALS.MINOR_7TH],
    'AUGMENTED MAJOR 7TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.AUGMENTED_5TH, INTERVALS.MAJOR_7TH],

    'DOMINANT 7#9': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH,
        INTERVALS.AUGMENTED_2ND],

    'DOMINANT 9TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH,
        INTERVALS.MAJOR_9TH],
    'DOMINANT 11TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH,
        INTERVALS.MAJOR_9TH, INTERVALS.PERFECT_11TH],
    'DOMINANT 13TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH,
        INTERVALS.MAJOR_9TH, INTERVALS.PERFECT_11TH, INTERVALS.MAJOR_13TH],

    'ADD 9': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_9TH],
    'ADD 4': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.PERFECT_4TH],
    'ADD 6': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH],
    '6/9': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MAJOR_9TH],
    '7/6': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH],
    'MIXED 3RD': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_3RD],

    'SUSPENDED 2ND': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.PERFECT_5TH],
    'SUSPENDED 4TH': [INTERVALS.ROOT, INTERVALS.PERFECT_4TH, INTERVALS.PERFECT_5TH],
    'JAZZ SUS': [INTERVALS.ROOT, INTERVALS.PERFECT_4TH, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH,
        INTERVALS.MAJOR_9TH],

    'MAJOR 7♯11': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_7TH,
        INTERVALS.SHARP_11TH],

    'MAJOR 6TH': [INTERVALS.ROOT, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH],
    'MINOR MAJOR 6TH': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH],

    // '': [],
};
