import { INTERVALS } from "../intervals";

export const SCALES: { [scaleName: string]: string[] } = {
    // pentatonic scales
    'MINOR PENTATONIC': [
        INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH],
    'MAJOR PENTATONIC': [
        INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH],
    'SUSPENDED': [
        INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.PERFECT_4TH, INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH],
    'BLUES MINOR': [
        INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH, INTERVALS.MINOR_6TH, INTERVALS.MINOR_7TH],
    'BLUES MAJOR': [
        INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.PERFECT_4TH, INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH],

    // heptatonic scales
    'MAJOR': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MAJOR_7TH],
    'MINOR': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MINOR_6TH, INTERVALS.MINOR_7TH],
    'HARMONIC MINOR': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MINOR_6TH, INTERVALS.MAJOR_7TH],
    'MELODIC MINOR': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MAJOR_7TH],
    // heptatonic modes
    'LYDIAN': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.AUGMENTED_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MAJOR_7TH],
    'MIXOLYDIAN': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH],
    'DORIAN': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH],
    'PHRYGIAN': [INTERVALS.ROOT, INTERVALS.MINOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MINOR_6TH, INTERVALS.MINOR_7TH],
    'LOCRIAN': [INTERVALS.ROOT, INTERVALS.MINOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.DIMINISHED_5TH, INTERVALS.MINOR_6TH, INTERVALS.MINOR_7TH],

    'FREYGISH': [INTERVALS.ROOT, INTERVALS.MINOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MINOR_6TH, INTERVALS.MINOR_7TH],
    'ALTERED DORIAN': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.AUGMENTED_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH],

    // octatonic scales
    'WHOLE-HALF DIMINISHED': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD,
        INTERVALS.PERFECT_4TH, INTERVALS.AUGMENTED_4TH, INTERVALS.AUGMENTED_5TH,
        INTERVALS.MAJOR_6TH, INTERVALS.MAJOR_7TH],
    'HALF-WHOLE DIMINISHED': [INTERVALS.ROOT, INTERVALS.MINOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.MAJOR_3RD,
        INTERVALS.AUGMENTED_4TH, INTERVALS.PERFECT_5TH,
        INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH],
    // bebop (add modes?)
    'BEBOP DOMINANT': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH, INTERVALS.MAJOR_7TH],
    'BEBOP MAJOR': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MAJOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.PERFECT_5TH, INTERVALS.AUGMENTED_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MAJOR_7TH],

    // Blues scales
    'BLUES HEXATONIC': [INTERVALS.ROOT, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH, INTERVALS.DIMINISHED_5TH,
        INTERVALS.PERFECT_5TH, INTERVALS.MINOR_7TH],
    'BLUES HEPTATONIC': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.PERFECT_4TH,
        INTERVALS.DIMINISHED_5TH, INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH],
    'BLUES NONATONIC': [INTERVALS.ROOT, INTERVALS.MAJOR_2ND, INTERVALS.MINOR_3RD, INTERVALS.MAJOR_3RD,
        INTERVALS.PERFECT_4TH, INTERVALS.PERFECT_5TH,
        INTERVALS.MAJOR_6TH, INTERVALS.MINOR_7TH, INTERVALS.MAJOR_7TH],

};

export const scale_aliases: { [scaleName: string]: string[] } = {
    'SUSPENDED': ['EGYPTIAN'],
    'BLUES MINOR': ['MAN GONG'],
    'BLUES MAJOR': ['RITSUSEN', 'YO'],
    'MAJOR': ['IONIAN'],
    'MINOR': ['AEOLIAN'],
};

// TODO: verify relative modality shifts of scales:
// const heptatonic_order : string[] = ['IONIAN', 'DORIAN', 'PHRYGIAN', 'LYDIAN', 'MIXOLYDIAN', 'AEOLIAN', 'LOCRIAN',];
